# Generated by Django 4.2.23 on 2025-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
