# Generated by Django 4.2.23 on 2025-07-25 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_userdetails_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='companyName',
            new_name='companyname',
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskname', models.CharField(blank=True, max_length=50)),
                ('taskdetails', models.CharField(blank=True, max_length=200)),
                ('duedate', models.CharField(blank=True, max_length=100)),
                ('iscompleted', models.BooleanField(blank=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
