# Generated by Django 4.2.23 on 2025-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_companyname_userdetails_companyname_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
