# Generated by Django 4.2.23 on 2025-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
