# Generated by Django 4.2.23 on 2025-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_duedate_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True),
        ),
    ]
